; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed, and extra flags
;   Library options: dependencies, extra library storages
;
; Docs: https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir  = firmware/RadarSystem
test_dir = tests

[env:uno]
platform  = atmelavr
board     = uno
framework = arduino
monitor_speed = 9600
lib_deps =
    arduino-libraries/Servo @ ^1.2.1

; Nano users can build with:  pio run -e nano
[env:nano]
platform  = atmelavr
board     = nanoatmega328
framework = arduino
monitor_speed = 9600
lib_deps =
    arduino-libraries/Servo @ ^1.2.1
